<%
path="upimg"'上传文件保存目录,默认是保存到后台的上一级目录upfile文件夹里
AllowExt="gif|jpg|jpeg|bmp|png"'允许上传的文件格式
maxsize=500'允许上传的文件格式
s_pic="yes"'是否生成缩略图
s_typ="yes"'是否固定尺寸
s_wid=127'宽度
s_hei=127'高度
s_mark_txt="no"'是否加文字水印
mark_txt="爱旺工业"'文字水印
%>